---
- name: java production servers
  hosts: "{{host}}"
  become: yes
  serial: 1
  roles:
    - java
  vars:
    project_name: "{{project_name}}"
    project_path: "/usr/home/package"
    origin_java_path: "/apps/files/package/cache_files"
